### PR TITLE
Add nnU-Net quick start guide

### PR DESCRIPTION
**Pull request by valosekj**
This PR drafts a nnU-Net quick start guide.

@tzebre, @rohanbanerjee, @naga-karthik, @plbenveniste, @Nilser3, @louisfb01  please update as you see fit. Thank you in advance!

Inspired by https://github.com/ivadomed/model-spinal-rootlets/issues/6. Thanks @tzebre!

### CODE REVIEW

**Review by jcohenadad — COMMENTED** [review]
Hey everyone! Thank you so much for taking the time to document this. I am a bit reluctant to insert the "how to train a nnUNET model" under the "GPU" section, because that section is specifically about GPU hardware, configuration, how to connect to them, what disks to use for scratch/home, etc.

Instead, I would suggest to create a repos called something like "training-nnunet" under the [ivadomed organization](https://github.com/ivadomed). Later on, we could always cross-reference that repos in our intranet (under GPUs, or at other places).

Also note that we need to think about the packaging of these models into SCT and possibly ADS. So, centralizing the documentation about training (what you are currently doing) and packaging (what you will do in the near future) would be wise.

**Comment by naga-karthik** [comment]
I would like to add that adding having this QuickStart guide would be more relevant inside the "Wiki" of a (potential) nnunet-specific repository in the ivadomed organization

**Comment by jcohenadad** [comment]
Wikis are often dismissed whereas `README.md` are _always_ seen. Also, the peer-review process on wikis (history of who committed what) is less straightforward. 

Note: You should cross-ref that nnUnet doc with https://github.com/ivadomed/data-conversion

**Comment by valosekj** [comment]
Thanks for the feedback!

> Instead, I would suggest to create a repos called something like "training-nnunet" under the [ivadomed organization](https://github.com/ivadomed).

Great idea! Agree! New repository under the ivadomed organization created: https://github.com/ivadomed/training-nnunet. Please, everyone, centralize all nnU-Net related stuff there.

> Note: You should cross-ref that nnUnet doc with https://github.com/ivadomed/data-conversion

Yes, cross-refed in https://github.com/ivadomed/training-nnunet#data-structure!

---

--> Closing the PR without merging

**Pull request closed without merging**
