### PR TITLE
Port to sphinx

### LINKED ISSUE #20: Port to sphinx
Port this wiki to be built by sphinx and hosted on Github pages, for all the same reasons as https://github.com/neuropoly/neuropoly-docs/issues/20.

### PR DESCRIPTION
**Pull request by kousu**
Fixes #20 

~~Demo at: https://intranet.wiki-demo.neuropoly.org~~
Live at: https://intranet.neuro.polymtl.ca

### CODE REVIEW

**Comment by kousu** [comment]
To actually publish on Github Pages, these manual steps need to be taken:

1. Log in to Namecheap, [find the domain](https://ap.www.namecheap.com/Domains/DomainControlPanel/neuropoly.org/advancedns), add `intranet.wiki-demo.` as a subdomain:

    Screenshot 2021-11-11 at 06-17-48 Advanced DNS

2. Go to the [Pages settings for this repo](https://github.com/neuropoly/neuropoly-internal-docs/settings/pages)

    1. Pick a publishing branch

        Screenshot from 2021-11-11 06-16-23

        Screenshot 2021-11-11 at 06-16-45 Build software better, together

        This is confusing because Github is asking what branch to build from; but we're already building with sphinx. The trick is to pick "gh-pages" as the branch; normally that would have jekyll's output (I think?) but because our Action automatically deploys a `.nojekyll` file, this works.


    2. Enable HTTPS

        Screenshot 2021-11-11 at 06-17-27 Build software better, together

**Comment by kousu** [comment]
Annnd it's up:

Screenshot 2021-11-11 at 06-22-07 🏠 Home — NeuroPoly Internal

**Comment by kousu** [comment]
Emailed dnsmaster@polymtl.ca last night per instructions at https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain to switch our DNS to say

```comms3$ dig intranet.neuro.polymtl.ca @9.9.9.9

; <<>> dig 9.10.8-P1 <<>> intranet.neuro.polymtl.ca @9.9.9.9
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19539
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;intranet.neuro.polymtl.ca.	IN	A

;; ANSWER SECTION:
intranet.neuro.polymtl.ca. 43200 IN	CNAME	neuropoly.github.io.
neuropoly.github.io.	3600	IN	A	185.199.110.153
neuropoly.github.io.	3600	IN	A	185.199.109.153
neuropoly.github.io.	3600	IN	A	185.199.111.153
neuropoly.github.io.	3600	IN	A	185.199.108.153
```

I had to tell Github about the change: https://github.com/neuropoly/neuropoly-internal-docs/pull/21/commits/f386c872451f9928642db8196adc39dde7306509, then I had to go back to https://github.com/neuropoly/neuropoly-internal-docs/settings/pages just now and wait for Github to be satisfied, and then reenable Force HTTPS:

Screenshot 2021-11-17 at 10-09-18 Build software better, together

One weird thing: the cache timeout seems very long. Github only set an hour (3600s) timeout on their DNS records, but ours is 24 days (86400s). This means that, in the rare case Github changes addresses, our site will be inaccessible for up to 3 weeks to different parts of the planet.

**Review by joshuacwnewton — APPROVED** [review]

**Comment by kousu** [comment]
I turned down everyone's permissions on https://app.gitbook.io, and de-synced Gitbook's copy:

<details>

2021-11-17-144330_592x836_scrot
2021-11-17-144333_499x237_scrot

</details>

Once this is merged I'll delete the Gitbook project/group too.

**Comment by kousu** [comment]
I went to namecheap and wiped all the DNS records I used for the demo address:

2021-11-17-145747_1109x386_scrot

**Pull request merged**
